apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - user-service/deployment.yaml
  - user-service/hpa.yaml
  - course-service/deployment.yaml
  - course-service/hpa.yaml
  - web-service/deployment.yaml
  - web-service/hpa.yaml
  - enrollment-service/deployment.yaml
  - payment-service/deployment.yaml
  - configmaps.yaml
  - secrets.yaml

